### ISSUE TITLE
error   pitch = np.arcsin(sinp)

### ISSUE THREAD

**Issue by VinceBeesley** [PyFlightCoach/FlightAnalysis#10]
Tom,
I am getting a,   pitch = np.arcsin(sinp) error while running the below file.
Everything completes ok and generates the template.
I have loaded the a25.py file to my flightAnalysis branch.   
Error:
PyFlightCoach/FlightAnalysis/examples/schedules_construction/a25.py
E:\PythonRepos\PyFlightCoach\.venv\Lib\site-packages\geometry\quaternion.py:99: RuntimeWarning: invalid value encountered in arcsin
  pitch = np.arcsin(sinp)

**Comment by ThomasDavid0** [comment]
This was a numpy warning that should have been fixed in the geometry module here: https://github.com/PyFlightCoach/geometry/commit/6b4005be86afd9719c383a6091f324ab2bba446f
