### ISSUE TITLE
question about transform_from and transform_to

### ISSUE THREAD

**Issue by kd0aij** [PyFlightCoach/FlightAnalysis#2]
https://github.com/PyFlightCoach/FlightAnalysis/blob/c709e92c19acb2eaba94fe935c03399c06e45e87/flightanalysis/section.py#L78

When breaking at this line using IPdb, flightline.transform_from.rotation and flightline.transform_to.rotation are identical.
Shouldn't they be inverses?

**Comment by ThomasDavid0** [comment]
They should be inverses, thanks, but I am a little surprised as I am sure I have used both with sensible results! I will investigate.

**Comment by ThomasDavid0** [comment]
I've been looking into this, the problem is in the geometry module, Transformation.from_coords() isn't working as expected.

**Comment by ThomasDavid0** [comment]
I've added failing tests to cover this issue

**Comment by ThomasDavid0** [comment]
closed with #7, thanks very much
