### ISSUE TITLE
missing heading in Box constructor call

### ISSUE THREAD

**Issue by kd0aij** [PyFlightCoach/FlightAnalysis#3]
https://github.com/PyFlightCoach/FlightAnalysis/blob/c709e92c19acb2eaba94fe935c03399c06e45e87/test/test_flightline.py#L18

Also, it seems that while you are using GPSPosition to specify the origin, the heading is specified in radians from the (ENU) x axis.
This is not consistent with GPS coords, since a GPS would report zero for North.

And how do you run your unit tests? The only way I have done it is by putting:
if __name__ == '__main__':
    unittest.main()

at the bottom of the file.
When I do that, test_directions fails for headings of zero and pi/2

**Comment by ThomasDavid0** [comment]
Thanks, I use a vscode extension to run unit tests, but will add that to the bottom of test files, also a few more tests to cover the box heading definition.

**Comment by kd0aij** [comment]
Thanks, I'll try switching to vscode for this project. The unittest integration seems pretty nice.

**Comment by ThomasDavid0** [comment]
I haven't been very good at keeping tests up to date, I tend to get a bit carried away making changes.

**Comment by ThomasDavid0** [comment]
I've added a few commits to your PR (https://github.com/PyFlightCoach/FlightAnalysis/pull/1), as this seems to be relevant to that. The test doesn't make sense on the Box class any more so I moved something similar to the FlightLine tests.

**Comment by ThomasDavid0** [comment]
Closed this as I have merged the PR
